/* eslint-disable max-len */
import DidYouKnow from "../../../reading/did-you-know"
import { BoldSpanText } from "../../../../bold-span-text"
import { CustomEinstein } from "../../../../icons/custom-einstein"
import { ReadingBlockHeader, ReadingBlockWithImage } from "../../../reading/reading-styles"

const whatIsLightBlocks: ContentBlock[] = [
	{
		id: "what-is-light-1",
		text: (
			<div>
				<ReadingBlockHeader>
					What is Light?
				</ReadingBlockHeader>
				<ReadingBlockWithImage>
					Think about watching a sunset or seeing Pip's LEDs glow in a dark room.
					In both cases, you're observing light in action.
					But what exactly is light? The answer might surprise you - light is more complex than it first appears.
				</ReadingBlockWithImage>
			</div>
		),
		action: { type: "continue" },
	},
	{
		id: "what-is-light-2",
		text: (
			<div>
				<ReadingBlockWithImage>
					Light is
					<BoldSpanText>
					a form of energy that travels through space as both a wave and a particle
					</BoldSpanText>
					- a concept called wave-particle duality.
					These particles of light, called photons, are like tiny packets of energy racing through space at
					an incredible speed of 300 million meters per second
					(that's fast enough to circle Earth 7.5 times in just one second!).
				</ReadingBlockWithImage>
				<DidYouKnow Icon={CustomEinstein}>
					The dual nature of light puzzled scientists for centuries. Albert Einstein's work on the photoelectric effect, which proved light behaves as both a wave and a particle, earned him the Nobel Prize in 1921.
				</DidYouKnow>
			</div>
		),
		action: {
			type: "quiz",
			quiz: {
				questions: [
					{
						question: "Which statement best describes the dual nature of light?",
						choices: [
							{
								answerChoiceId: 1,
								text: "Light only behaves as a wave in space",
								correct: false,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 2,
								text: "Light is a form of energy that exhibits both wave and particle properties",
								correct: true,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 3,
								text: "Light consists only of particles called electrons",
								correct: false,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 4,
								text: "Light travels as waves but transforms into particles when it hits objects",
								correct: false,
								explanation: "Test explanation"
							}
						],
						questionUUID: "kdnbjkasdka" as QuestionUUID
					}
				]
			}
		}
	},
	{
		id: "what-is-light-3",
		text: (
			<ReadingBlockWithImage>
				When photons interact with something (like Pip’s casing or your eyes), they can do three things:
				<ul>
					<li>Bounce off (reflection) - like a ball bouncing off a wall</li>
					<li>Pass through (transmission) - like sunlight through a window</li>
					<li>Get absorbed - like a sponge soaking up water</li>
				</ul>
			</ReadingBlockWithImage>
		),
		action: { type: "continue" },
	},
	{
		id: "what-is-light-4",
		text: (
			<ReadingBlockWithImage>
				Understanding these interactions helps us design Pip's sensors and indicators. For instance, Pip's clear casing needs to transmit light from its LEDs, while its light sensors need to absorb photons to detect obstacles
			</ReadingBlockWithImage>
		),
		action: { type: "continue"}
	},
	{
		id: "what-is-light-5",
		text: (
			<ReadingBlockWithImage>
				When you see Pip's green status light, you're actually seeing photons that have:
				1. Been generated by the LED
				2. Transmitted through its clear casing
				3. Reflected off various surfaces
				4. Finally been absorbed by the light-sensitive cells in your eyes
			</ReadingBlockWithImage>
		),
		action: { type: "continue"}
	},
	{
		id: "what-is-light-6",
		text: null,
		action: {
			type: "quiz",
			quiz: {
				questions: [
					{
						question: "A photon from Pip's LEDs hits a semi-transparent plastic surface. What is the MOST likely outcome?",
						choices: [
							{
								answerChoiceId: 1,
								text: "The photon will only be reflected",
								correct: false,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 2,
								text: "The photon will only be absorbed",
								correct: true,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 3,
								text: "Some photons will be reflected, some transmitted, and some absorbed",
								correct: true,
								explanation: "Test explanation"
							},
							{
								answerChoiceId: 4,
								text: "The photon will split into two smaller photons",
								correct: false,
								explanation: "Test explanation"
							}
						],
						questionUUID: "kdnbjkasd222ka" as QuestionUUID
					}
				]
			}
		}
	}
]

export default whatIsLightBlocks
